name: Deployment 

#to deploy the code manually 
on: workflow_dispatch

jobs:
  deploy:
    name: Static Website Deployment on S3 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{secrets.CONFIGURE_AWS_CREDENTIALS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.ACONFIGURE_AWS_CREDENTIALS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1
      
      - name: Deploy static site to S3
        run: 
          aws s3 sync ./css s3://maungzin.com 
          aws s3 sync ./ s3://maungzin.com 

